resolver: lts-12.2

flags: {}

packages:
  - '.'
  - location:
      git: git://github.com/bitnomial/hs-vault-tool
      commit: bd78b967e5420d38193cba61082aadb00d2c1dc4
    extra-dep: true
    subdirs:
      - vault-tool

extra-deps: []
